### ISSUE TITLE
Article missing links for access (add escholarship)

### ISSUE THREAD

**Issue by Vensberg** [ucd-library/rp-ucd-harvest#37]
This publication in ]https://sandbox.experts.ucdavis.edu/work/2478058 doesn't have info in the Publication Records section. However, UC Links should be present and eventually take the user to https://escholarship.org/uc/item/2m4110qb. [Could this be another self-entered publication with missing links?]

**Comment by qjhart** [comment]
@Vensberg, in this case the UC-elinks does not do anything useful.  However, since the citation includes an Escholarship link, we can access  the data via that.  This is interesting, in that we should see if that link exists for any publication. Then, we need to figure out how to represent that to the experts system.  Of the cuff, I'd say we add a new predicate for ARKS and use the standard ARK resolver, since that's so similar to DOI's 

Regardless, that will have to wait for the next sprint.

**Comment by jrmerz** [comment]
I'm moving this card v1.3 and setting as a triage
